spring.application.name=JWTDemo

# Static Resources
spring.web.resources.static-locations=file:./src/main/resources/static/,classpath:/static/
spring.web.resources.cache.period=0

# PostgreSQL Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.secret=9b8ca42793398680a5e3cd6ea3ae52c35c16d96f2973e8e066acc91cf17019ea
app.jwt.expiration-ms=3600000

# Razorpay Configuration
razorpay.key-id=rzp_test_Sgy1vgpGLBLZLO
razorpay.key-secret=FH2irfnjYZPK6UQq4JLML9tA
razorpay.currency=INR

# BREVO MAIL CONFIGURATION

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=rsanju.3312@gmail.com
spring.mail.password=xsmtpsib-3584be9d4407e829b7789bc25b4b5df5c846925e161d86114945c39843efb43d-mkARzPsclQYoz6T1

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Base URL
app.base-url=${APP_BASE_URL}

# Render Port
server.port=${PORT:8080}
